call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-surround'
Plug 'Raimondi/delimitMate'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/syntastic'
Plug 'ervandew/supertab'
Plug 'bling/vim-airline'
Plug 'altercation/vim-colors-solarized'
Plug 'mtth/scratch.vim'
"Plug 'flatcap/vim-scratch'
" Plug 'python-mode/python-mode'
call plug#end()
set number
set mouse=a
map <ScrollWheelUp> <C-Y>
map <ScrollWheelDown> <C-E>
let mapleader=","
syntax on
filetype plugin indent on
set background=dark
colorscheme solarized
set laststatus=2
let g:airline_powerline_fonts=1
set tabstop=8
set softtabstop=0
set shiftwidth=4
set smarttab
set expandtab

" For editing gzipped files without unzipping
augroup gzip
    autocmd!
    autocmd BufReadPre,FileReadPre *.gz set bin
    autocmd BufReadPost,FileReadPost   *.gz '[,']!gunzip
    autocmd BufReadPost,FileReadPost   *.gz set nobin
    autocmd BufReadPost,FileReadPost   *.gz execute ":doautocmd BufReadPost " . expand("%:r")
    autocmd BufWritePost,FileWritePost *.gz !mv <afile> <afile>:r
    autocmd BufWritePost,FileWritePost *.gz !gzip <afile>:r
    autocmd FileAppendPre      *.gz !gunzip <afile>
    autocmd FileAppendPre      *.gz !mv <afile>:r <afile>
    autocmd FileAppendPost     *.gz !mv <afile> <afile>:r
    autocmd FileAppendPost     *.gz !gzip <afile>:r
augroup END']'

" For scratch buffers
let g:scratch_top = 0
