# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt extendedglob
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/arnav/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Load antigen
source ~/.dotfiles/antigen/antigen.zsh

# Syntax highlighting bundle
antigen bundle zsh-users/zsh-syntax-highlighting

# Pure prompt bundle
antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

# Tell antigen you're done
antigen apply

if [ -d /etc/profile.d ]; then
    setopt no_nomatch
    for i in /etc/profile.d/*.sh; do
        if [ -r $i ]; then
            . $i
        fi
    setopt nomatch
    done
fi

# HTCF-specific options
if [ $(uname) = "Linux" ]; then
    eval `dircolors ~/.dotfiles/dircolors-solarized/dircolors.ansi-dark`
    alias ls='ls --color'
    alias sl='ls --color'
    alias grep='grep --color=auto'
    alias queue='squeue | grep '`whoami`

    # Conda
    export PATH="/home/arnav/.miniconda3/bin/:"$PATH

    # Import key modules
    module load tmux
    module load imgcat
    module -q load transferData
    module load samtools
    module load bedtools
    module load bedops
    module load java
    module -q load drop-seq-tools
    module load cutadapt
    module load novoalign
fi

# macOS-specific options
if [ $(uname) = "Darwin" ]; then
    eval `gdircolors ~/.dotfiles/dircolors-solarized/dircolors.ansi-dark`
    alias ls='gls --color'
fi

# Nifty one-liner for adding numbers in shell
alias add="awk '{ sum += \$1; } END { print sum; }' \"$@\""

# Alias to ccat (cat with syntax highlighting)
alias ccat=~/ccat-linkx-amd64-1.1.0/ccat

# -- Improved X11 forwarding through GNU Screen (or tmux).
# From http://alexteichman.com/octo/blog/2014/01/01/x11-forwarding-and-terminal-multiplexers/
# If not in screen or tmux, update the DISPLAY cache.
# If we are, update the value of DISPLAY to be that in the cache.
function update-x11-forwarding
{
    if [ -z "$STY" -a -z "$TMUX" ]; then
        echo $DISPLAY > ~/.display.txt
    else
        export DISPLAY=`cat ~/.display.txt`
    fi
}

# This is run before every command.
preexec() {
    # Don't cause a preexec for PROMPT_COMMAND.
    # Beware!  This fails if PROMPT_COMMAND is a string containing more than one command.
    [ "$BASH_COMMAND" = "$PROMPT_COMMAND" ] && return

    update-x11-forwarding

    # Debugging.
    #echo DISPLAY = $DISPLAY, display.txt = `cat ~/.display.txt`, STY = $STY, TMUX = $TMUX
}
trap 'preexec' DEBUG
